@extends('layouts.app')

@section('content')
      @if (Page::slug() == 'home')
        @include('component::news.feed')
        @include('component::gallery.feed')
        @include('component::shop.hero')
        @include('component::shop.gender-block')
        @include('component::field-report.feed')
      @elseif (Page::slug() == 'news')
        @include('component::news.feed')
      @elseif (Page::slug() == 'gallery')
        @include('component::gallery.feed')
      @elseif (Page::slug() == 'shop')
        @include('component::shop.hero')
        @include('component::shop.gender-block')
      @elseif (Page::slug() == 'field-report')
        @include('component::field-report.feed')
      @endif
@endsection
